# Generated by Django 6.0.3 on 2026-04-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='period',
            field=models.CharField(default='D', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='profit_ln',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='profit_simple',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
