# Generated by Django 6.0.3 on 2026-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_share_period_share_profit_ln_share_profit_simple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='profit_ln',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='profit_simple',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
    ]
